# 上下文初始化加载
info:
   name: Eureka server
   contact: 动脑科技VIP

spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
server:
  port: 8761
eureka:
  client:
    # 是否注册到eurekaserver
    register-with-eureka: true
    # 是否拉取信息
    fetch-registry: false
    # eureka server地址
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    hostname: localhost
